route:
  group_by: ['cluster']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 10m
  receiver: 'Prometheus'
receivers:
- name: 'Prometheus'
  pagerduty_configs:
  - service_key: 'PAGERDUTY_INTEGRATION_KEY' # Update PagerDuty Integration Key