{
 "title": "Validator stats",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "validator", "query": { "query": "label_values(validator_name)" } },
   {
    "name": "server_name",
    "query": {
     "query": "label_values(validator_version_info{validator_name=\"$validator\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "validator penalty",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_ledger{subtype!=\"total\", validator_name=\"$validator\"}",
     "legendFormat": "penalty-{{subtype}}"
    },
    {
     "expr": "validator_inconsensus{validator_name=~\"$validator|\"}",
     "legendFormat": "consensus"
    }
   ]
  },
  {
   "title": "api balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_api_balance{validator_name=\"$validator\"}",
     "legendFormat": "$validator"
    }
   ]
  },
  {
   "title": "validator version",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "validator_version_info{validator_name=\"$validator\"}"
    }
   ]
  },
  {
   "title": "block age vs sessions vs connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_block_age{validator_name=\"$validator\"}",
     "legendFormat": "block age"
    },
    {
     "expr": "validator_sessions{validator_name=\"$validator\"}",
     "legendFormat": "session count"
    },
    {
     "expr": "validator_connections{validator_name=\"$validator\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "cpu load vs memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=~\"$validator\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{job=~\"$validator\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"$validator\"}/(1024^3)",
     "legendFormat": "avail mem"
    }
   ]
  },
  {
   "title": "disk utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=~\"$validator\"}[15m]) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "network traffic vs cpu freq",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{device=\"eth0\",job=~\"$validator\"}[5m])/(1024^2)",
     "legendFormat": "TX"
    },
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"eth0\",job=~\"$validator\"}[5m])/(1024^2)",
     "legendFormat": "RX"
    },
    {
     "expr": "max(node_cpu_scaling_frequency_hertz{job=~\"$validator\"})",
     "legendFormat": "core speed"
    }
   ]
  },
  {
   "title": "disk IO vs latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{job=~\"$validator\",device!=\"md0\"}[2m])",
     "legendFormat": "queue len {{device}}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{job=~\"$validator\",device!=\"md0\"}[2m])/rate(node_disk_writes_completed_total{job=~\"$validator\",device!=\"md0\"}[2m])",
     "legendFormat": "latency {{device}}"
    }
   ]
  },
  {
   "title": "cpu temp vs fan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(node_hwmon_temp_celsius{job=~\"$validator\"})",
     "legendFormat": "cpu temp"
    },
    {
     "expr": "max(node_ipmi_speed_rpm{job=~\"$validator\"})",
     "legendFormat": "max fan"
    }
   ]
  }
 ]
}